config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :people
  resources :orders
  resources :products

  root to: 'order_products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :set_order_product, only: %i[ show edit update destroy ]

  def consulta
    @tabela_consulta1 = Person.all
    @tabela_consulta2 = Product.all
    @tabela_consulta3 = Order.find_by_sql("SELECT * FROM orders INNER JOIN people ON people.id = orders.person_id WHERE people.name = 'Jose'")
    @tabela_consulta4 = Order.find_by_sql("SELECT orders.description as compra, products.description, products.id, people.id, people.name FROM ((orders INNER JOIN people on people.id = orders.person_id)
			   INNER JOIN PRODUCTS ON PRODUCTS.ID = ORDERS.PRODUCT_ID) WHERE PRODUCTS.DESCRIPTION = 'Arroz'")
  end
  
  
  # GET /order_products or /order_products.json
  def index
    @order_products = OrderProduct.all
    consulta 
  end 

  # GET /ord er_products/1 or /order_products/1.json
  def show
    @orders = Order.all 
  end


  # GET /order_products/new
  def new 
    @order_product = OrderProduct.new
  end

  # GET /order_products/1/edit
  def edit
  end

  # POST /order_products or /order_products.json
  def create
    @order_product = OrderProduct.new(order_product_params)

    respond_to do |format|
      if @order_product.save
        format.html { redirect_to order_product_url(@order_product), notice: "Order product was successfully created." }
        format.json { render :show, status: :created, location: @order_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_products/1 or /order_products/1.json
  def update
    respond_to do |format|
      if @order_product.update(order_product_params)
        format.html { redirect_to order_product_url(@order_product), notice: "Order product was successfully updated." }
        format.json { render :show, status: :ok, location: @order_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_products/1 or /order_products/1.json
  def destroy 
    @order_product.destroy 
 
    respond_to do |format|
      format.html { redirect_to order_products_url, notice: "Order product was successfully destroyed." }
      format.json { head :no_content } 
    end 
  end 

  private 
    # Use callbacks to share common setup or constraints between actions.
    def set_order_product 
      @order_product = OrderProduct.find(params[:id]) 
    end 
 
    # Only allow a list of trusted parameters through.
    def order_product_params 
      params.require(:order_product).permit(:order_id, :product_id, :ammount)
    end 
end 

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/views/order_products/_form.html.erb
<%= form_with(model: order_product, local: true) do |form| %>
  <% if order_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_product.errors.count, "error") %> prohibited this order_product from being saved:</h2>

      <ul>
      <% order_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :ammount %>
    <%= form.number_field :ammount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_products/edit.html.erb
<h1>Editing Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Show', @order_product %> |
<%= link_to 'Back', order_products_path %>

app/views/order_products/index.html.erb
<head>

  <div class="mt-4 p-5 bg-info text-dark">
    <h1> Carrinho de compras</h1>
  </div>
</head>
<body>


<nav class="navbar bg-dark ">

  <div class="container-fluid">
    <ul class="nav -nav-tabs">
      <li class="nav-item bg-light">
        <%= link_to 'Pessoas', people_path, class:"nav-link" %>
      </li>
      <li class="nav-item bg-light">
        <%= link_to 'Produtos', products_path, class:"nav-link" %>
      </li>
      <li class="nav-item bg-light">
        <%= link_to 'Pedidos/Compras', orders_path, class:"nav-link" %>
      </li>
    </ul>
  </div>

</nav>

<strong><h5>  Querys <span class="badge bg-secondary">Desafio 3 Parte 3: </h5></strong>

<br>

<div class="container-fluid">
      <div class="row">
        <div class="col-4">
          <table class="table table-bordered table-secondary">
            <p class="lead">Tabela da consulta 1 : listar todas as pessoas:</p>
            <% @tabela_consulta1.each do |consulta| %>
              <thead>
              <tr>
                <th scope="col"> Nome: <%= consulta.name %> </th>
              </tr>
              </thead>
            <% end %>
          </table>
        </div>
        <div class="col-4">
          <table class="table table-bordered table-secondary">
            <p class="lead">Tabela da consulta 2 : listar todos os produtos:</p>
            <% @tabela_consulta2.each do |consulta| %>
              <thead>
              <tr>
                <th scope="col"> Produto: <%= consulta.description %> </th>
              </tr>
              </thead>
            <% end %>
          </table>
        </div>
      </div>
    </div>


<br>

<div class="container-fluid">
  <div class="row justify-content-start">
    <div class="col-5">
      <p class="lead">Tabela da consulta 3: listar compras onde a pessoa 'Jose' faz parte: </p>
      <table class="table table-bordered table-secondary">
        <% @tabela_consulta3.each do |consulta| %>
          <thead>
          <tr>
            <th scope="col"> Identificação da compra: <%= consulta.description %> </th>
            <th scope="col"> Comprador: <%= consulta.person.name %> </th>
          </tr>
          </thead>
        <% end %>
      </table>
    </div>
    <div class="col-5">
      <p class="lead">Tabela da consulta 4 : listar compras com nome do comprador onde existe o produto 'Arroz':</p>
      <table class="table table-bordered table-secondary">
        <% @tabela_consulta4.each do |consulta| %>
          <thead>
          <tr>
            <th scope="col"> Identificação da compra: <%= consulta.compra %> </th>
            <th scope="col"> Produto: <%= consulta.description %> </th>
            <th scope="col"> Comprador: <%= consulta.name %> </th>
          </tr>
          </thead>
        <% end %>
      </table>
    </div>
  </div>
</div>

<br>

</body>

app/views/order_products/new.html.erb
<h1>New Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Back', order_products_path %>

app/views/order_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_product.order.description %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_product.product.description %>
</p>


<p>
  <strong>Ammount:</strong>
  <%= @order_product.ammount %>
</p>

<%= link_to 'Edit', edit_order_product_path(@order_product) %> |
<%= link_to 'Back', order_products_path %>